import type { Metadata } from 'next'
import React from "react";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <div className="justify-center items-center flex h-screen">
            {children}
        </div>
    )
}
